server:
  port: 8080
  read_timeout: 5
  write_timeout: 10
  shutdown_timeout: 5
  trusted_proxies:
    - 127.0.0.1
    - 10.0.0.0/8

proxy:
  timeout: 30
  max_idle_conns: 100
  idle_conn_timeout: 90
  enable_cache: true
  cache_ttl: 60

security:
  enable_jwt: false
  jwt_secret: "your-jwt-secret-key-here"
  enable_api_key: false
  api_keys:
    - "your-api-key-1"
    - "your-api-key-2"
  enable_tls: false
  tls_cert_file: "cert.pem"
  tls_key_file: "key.pem"
  enable_cors: true
  cors_allow_origins:
    - "http://consumer-service.crash-game-backend-local.svc.cluster.local"
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost"
    - "http://api-gateway.gateway"
    - "http://api-gateway"

resilience:
  enable_circuit_breaker: false
  failure_threshold: 5
  reset_timeout: 30
  enable_retry: false
  max_retries: 3
  retry_interval: 100

logging:
  level: "debug"
  format: "json"
  output_path: "stdout"

metrics:
  enable: true
  path: "/metrics"

tracing:
  enable: true
  jaeger_endpoint: "localhost:4318"
  service_name: "api-gateway"

services:
  # Crash Game API Service
  - name: "ice-age-royal-api"
    base_path: "/games/ice-age-royal"
    targets:
      - "http://api-service.crash-game-backend-local.svc.cluster.local"
    strip_base_path: true
    enable_websocket: false
    enable_sticky_session: false
    headers:
      X-Service: "ice-age-royal-api"
      X-Source: "api-gateway"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5

  # Crash Game WebSocket Consumer Service
  - name: "ice-age-royal-consumer"
    base_path: "/games/ice-age-royal/consumer"
    targets:
      - "http://consumer-service.crash-game-backend-local.svc.cluster.local"
    strip_base_path: true
    enable_websocket: true
    enable_sticky_session: true
    headers:
      X-Service: "ice-age-royal-consumer"
      X-Source: "api-gateway"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5

  # Crash Game WebSocket Interaction Service
  - name: "ice-age-royal-interaction"
    base_path: "/games/ice-age-royal/interaction"
    targets:
      - "http://interaction-service.crash-game-backend-local.svc.cluster.local"
    strip_base_path: true
    enable_websocket: true
    enable_sticky_session: true
    headers:
      X-Service: "ice-age-royal-interaction"
      X-Source: "api-gateway"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5
