server:
  port: 8080
  read_timeout: 5
  write_timeout: 10
  shutdown_timeout: 5
  trusted_proxies:
    - 127.0.0.1
    - 10.0.0.0/8

proxy:
  timeout: 30
  max_idle_conns: 100
  idle_conn_timeout: 90
  enable_cache: true
  cache_ttl: 60

security:
  enable_jwt: false
  jwt_secret: "your-jwt-secret-key-here"
  enable_api_key: false
  api_keys:
    - "your-api-key-1"
    - "your-api-key-2"
  enable_tls: false
  tls_cert_file: "cert.pem"
  tls_key_file: "key.pem"
  enable_cors: true
  cors_allow_origins:
    - "*"

resilience:
  enable_circuit_breaker: true
  failure_threshold: 5
  reset_timeout: 30
  enable_retry: true
  max_retries: 3
  retry_interval: 100

logging:
  level: "info"
  format: "json"
  output_path: "stdout"

metrics:
  enable: true
  path: "/metrics"

services:
  - name: "user-service"
    base_path: "/api/users"
    targets:
      - "http://localhost:8081"
    strip_base_path: true
    enable_websocket: false
    enable_sticky_session: false
    headers:
      X-Service: "user-service"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5

  - name: "product-service"
    base_path: "/api/products"
    targets:
      - "http://localhost:8082"
    strip_base_path: true
    enable_websocket: false
    enable_sticky_session: false
    headers:
      X-Service: "product-service"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5

  - name: "chat-service"
    base_path: "/api/chat"
    targets:
      - "http://localhost:8083"
    strip_base_path: true
    enable_websocket: true
    enable_sticky_session: true
    headers:
      X-Service: "chat-service"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5

  - name: "socketio-service"
    base_path: "/games/ice-age-royal/consumer"
    targets:
      - "http://consumer-service.crash-game-backend-local.svc.cluster.local"
    strip_base_path: true
    enable_websocket: true
    enable_sticky_session: true
    headers:
      X-Service: "socketio-service"
      X-Source: "api-gateway"
    health_check:
      path: "/health"
      interval: 30
      timeout: 5
